modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
[[mods]]
modId = "tipthescales"
version = "${file.jarVersion}"
displayName = "TipTheScales"
authors = "Jaredlll08"
logoFile="icon.png"
updateJSONURL = "https://updates.blamejared.com/get?n=TipTheScales&gv=1.18.1"
description = '''
Allows for more control when adjusting the GUI size.
'''